apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
# コンテナ
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybotapp-mysql-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybotapp-mysql-dev
  template:
    metadata:
      labels:
        app: mybotapp-mysql-dev
    spec:
      containers:
        - name: mybotapp-mysql-dev-container
          # https://hub.docker.com/_/postgres/?tab=tags
          # 事前にdocker pull mariadbしておく
          image: mariadb:latest
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: TZ
              value: Asia/Tokyo
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: pv-slow-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: nfs
    environment: development
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    # 作業者の環境によって変更
    path: "/Users/takehikoogasawara/Documents/workspace/docker-rails-mysql/mysql/data"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-slow-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow