source 'https://rubygems.org'
gem 'rails', '~> 6'

gem 'mysql2'

# Use Puma as the app server
gem 'puma', '~> 4.1'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 6.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
gem 'webpacker', '~> 4.0'

gem 'httpclient'
gem 'rack-mini-profiler'
gem 'kaminari'
gem 'config'
gem 'activerecord-session_store'
gem 'jp_prefecture'
gem 'font-awesome-rails'
gem 'better_errors'
gem 'rspec-rails'
gem 'devise'
# gem 'bundler'
gem 'bootsnap', '>= 1.4.2'
gem 'byebug'
gem 'web-console', '>= 3.3.0'
gem 'listen', '~> 3.2'
gem 'spring'
gem 'spring-watcher-listen', '~>2.0.0'
gem 'capybara', '>=2.15'
gem 'selenium-webdriver'
gem 'webdrivers'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development do
  gem "awesome_print"
end